version: '2'
services:
    coininvess-app:
        image: coininvess
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://coininvess-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=coininvess
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    coininvess-mongodb:
        extends:
            file: mongodb.yml
            service: coininvess-mongodb
